name: Feature Request
description: Suggest a new feature for UAICP reference implementations
title: "[FEATURE] "
labels: ["✨ Feature", "🔍 Needs Triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for the UAICP reference implementation!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Describe the problem or limitation you're experiencing
      placeholder: |
        I'm trying to [use case] but I can't because [limitation/problem].
        This affects [who/what] when [scenario].
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen
      placeholder: |
        I would like the ability to [desired functionality].
        
        For example:
        ```typescript
        // Proposed API usage
        const result = await component.newMethod({
          parameter: 'value'
        });
        ```
        
        This would solve [problem] by [explanation].
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Which component would this affect?
      multiple: true
      options:
        - Universal Discovery Mesh
        - Protocol Translation Hub
        - Adaptive Router
        - Capability Negotiator
        - Integration Examples
        - Testing Framework
        - Performance Tools
        - Developer Tools
        - Documentation
        - CI/CD Pipeline
        - New Component
        - Other
    validations:
      required: true

  - type: dropdown
    id: protocol_impact
    attributes:
      label: Protocol Integration Impact
      description: How does this feature affect protocol integrations?
      multiple: true
      options:
        - MCP (Model Context Protocol)
        - OpenAI API
        - Google A2A
        - All Protocols
        - Protocol-Agnostic
        - New Protocol Support
        - Cross-Protocol Functionality
        - Other
    validations:
      required: false

  - type: dropdown
    id: implementation_effort
    attributes:
      label: Implementation Effort Estimation
      description: What's your estimate of the implementation complexity?
      options:
        - 🟢 Small (< 1 week) - Simple API addition or bug fix
        - 🟡 Medium (1-4 weeks) - New feature or significant enhancement
        - 🟠 Large (1-3 months) - Major component or architectural change
        - 🔴 Extra Large (> 3 months) - New core component or breaking change
        - ❓ Unknown - Need technical investigation
    validations:
      required: true

  - type: dropdown
    id: breaking_changes
    attributes:
      label: Backward Compatibility
      description: Would this feature introduce breaking changes?
      options:
        - ✅ Fully backward compatible - No breaking changes
        - ⚠️ Minor compatibility impact - Deprecated methods/options
        - ❌ Breaking changes required - API or behavior changes
        - ❓ Needs compatibility analysis
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you and the community?
      options:
        - 🔥 Critical - Blocking adoption or major use cases
        - ⚡ High - Important for widespread adoption
        - 📈 Medium - Would enhance developer experience
        - 📋 Low - Nice to have enhancement
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case and Examples
      description: Provide specific use cases and examples
      placeholder: |
        **Use Case 1**: [Specific scenario]
        - Current limitation: [What can't be done today]
        - Proposed solution: [How this feature helps]
        - Example usage: [Code or workflow example]
        
        **Use Case 2**: [Another scenario if applicable]
        ...
        
        **Real-world example**: [Specific project or implementation]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        - Alternative 1: [Description and why it's not ideal]
        - Alternative 2: [Description and limitations]
        - Workaround: [Current workaround being used]
        - External solutions: [Tools or libraries that partially solve this]
    validations:
      required: false

  - type: textarea
    id: implementation_ideas
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        **Approach**: [High-level implementation approach]
        
        **API Design**:
        ```typescript
        // Proposed interface or method signatures
        interface NewFeature {
          method(params: ParamType): Promise<ReturnType>;
        }
        ```
        
        **Considerations**:
        - Performance impact: [Expected impact]
        - Testing requirements: [What needs to be tested]
        - Documentation needs: [What docs need updates]
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, links, or examples
      placeholder: |
        - Related issues: [Links to related issues]
        - External references: [Links to documentation, RFCs, etc.]
        - Community discussion: [Links to discussions]
        - Similar implementations: [Examples from other projects]
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Would you be interested in contributing to this feature?
      options:
        - label: I'd like to work on this feature myself
        - label: I can provide guidance and review
        - label: I can help with testing
        - label: I can help with documentation
        - label: I'm interested but need mentoring

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify you've completed these steps
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have provided clear use cases and examples
          required: true
        - label: I have considered implementation complexity
          required: true
        - label: I agree to follow the Code of Conduct
          required: true
